---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  "An encrypted S3 Bucket on AWS with CloudFormation"

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: AES256

      BucketName: !Sub "festiveox-pinkrubberboots-${AWS::AccountId}-${AWS::Region}"

